# Generated by Django 4.0.4 on 2022-07-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_suscripcion_user_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='dirección'),
        ),
    ]
