# Generated by Django 4.0.4 on 2022-07-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suscripcion',
            field=models.BooleanField(default=False),
        ),
    ]
