# Generated by Django 4.0.1 on 2022-05-19 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='idCtegoria',
            new_name='idCategoria',
        ),
    ]
