# Generated by Django 4.0.4 on 2022-07-10 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
