# Generated by Django 4.0.4 on 2022-05-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='precio del producto'),
            preserve_default=False,
        ),
    ]
