# Generated by Django 4.0.1 on 2022-05-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
           fields=[
               ('idCtegoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
               ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
    ]